### ISSUE TITLE
XCFramework Support

### ISSUE THREAD

**Issue by justinvallely** [radarlabs/radar-sdk-ios#106]
## Summary
With the introduction of M1 chips, Apple is shifting from "fat" frameworks to XCFrameworks and will soon require all packages to be shipped this way. Is this something Radar is actively working to support soon?

## OS version
Xcode 12+

## SDK installation method
Carthage, Cocoapods, SPM

**Comment by nickpatrick** [comment]
Hey @justinvallely, we will investigate and get back to you this week. Stay tuned.

**Comment by nickpatrick** [comment]
@justinvallely Is this causing build issues for you today, or just something you're planning ahead for?

**Comment by justinvallely** [comment]
Hey @nickpatrick. No build issues yet. We have our own post-build scripts to manually strip architectures out of frameworks like Radar. Having a XCFramework though, we'd get that for free from Xcode. We are hearing that Apple will force XCFrameworks sometime in April and we're trying to get ahead of it here at Ibotta.

**Comment by nickpatrick** [comment]
Thanks @justinvallely, makes sense. We'll add support for this in the next week or two. We have a prototype working, just need to test and work through the logistics of distributing the `.xcframework` through CocoaPods. Will keep this issue updated!

**Comment by justinvallely** [comment]
Thank you! I'll keep an eye on the releases. Let me know if we can help.

**Comment by nickpatrick** [comment]
@justinvallely XCFramework and Swift Package Manager support were added in the https://github.com/radarlabs/radar-sdk-ios/releases/tag/3.2.0-beta.1 release. Give it a try and let us know if it works for you. A non-beta `3.2.0` release will be coming in the next few weeks.
