### ISSUE TITLE
Radar.startTracking(trackingOptions: .efficient) not working

### ISSUE THREAD

**Issue by DavidTomic** [radarlabs/radar-sdk-ios#117]
## Summary
I tried in my projekt implement background tracking but it is not working.
I also tried test it using the your Example project and it is not wokring.

## Code to reproduce
```
let options = RadarTrackingOptions.efficient
options.sync = .all
Radar.startTracking(trackingOptions: options)
```

## Steps to reproduce
Run Example project, give all location and notification permissions, use RadarTrackingOptions.efficient for Radar.startTracking, move around the city and issue is that didReceiveEvents never get called.

## OS version
iPhone 12, iOS 14.3

## SDK installation method
Clone and run your Example (I set my publishableKey "prj_test_pk_ffXXXX...)

## SDK version
I think it is 3.1.8, that is what I see in RadarUtils class  -> (NSString *)sdkVersion

## Other information
I provided all location and notification permissions, methods didUpdateLocation and didUpdateClientLocation working ok, but didReceiveEvents never get called.
Also I see no Events records in Radars Web Dashboard.

**Comment by nickpatrick** [comment]
Hey @DavidTomic, if you're seeing `didUpdateLocation()` callbacks, that means that `startTracking()` is working. To get `didReceiveEvents()` callbacks, you'll need to create geofences first (https://radar.io/documentation/geofences). If you create geofences and trigger location updates inside those geofences, you should get `didReceiveEvents()` callbacks for `user.entered_geofence` events and you should also see those events in the dashboard.

**Comment by bukerapp** [comment]
@nickpatrick thank you for your response.

I am not looking for geofence events but places event:
"Places uses our place database to detect when a user visits a place, chain, or category, even if you haven't set up geofences for those places."

I have enabled Places in settings and checked "user.entered_place" and "user.exited_place".

Maybe the problem is that I do not have Team pricing enabled.

Can I test this without Team pricing?

**Comment by DavidTomic** [comment]
@nickpatrick thank you for your response.

I am not looking for geofence events but places event:
"Places uses our place database to detect when a user visits a place, chain, or category, even if you haven't set up geofences for those places."

I have enabled Places in settings and checked "user.entered_place" and "user.exited_place".

Maybe the problem is that I do not have Team pricing enabled.

Can I test this without Team pricing?

**Comment by nickpatrick** [comment]
That's right, Places is only available on Team or higher. Feel free to upgrade or apply for our Startup Program here: https://radar.io/startups
