### ISSUE TITLE
Support Static RadarSDK.xcframework

### ISSUE THREAD

**Issue by hendych** [radarlabs/radar-sdk-ios#148]
## Summary
Support static xcframework instead of using dynamic xcframework. Using dynamic xcframework would reduce the app start up launch time.

## Code to reproduce
N/A

## Steps to reproduce
Using `Terminal` you can see if the xcframework is dynamic or static.
```Bash
file Pods/RadarSDK/dist/RadarSDK.xcframework/ios-arm64_armv7/RadarSDK.framework/RadarSDK
```

### If dynamic the output should be
```Bash
Pods/RadarSDK/dist/RadarSDK.xcframework/ios-arm64_armv7/RadarSDK.framework/RadarSDK: Mach-O universal binary with 2 architectures: [arm_v7:Mach-O dynamically linked shared library arm_v7] [arm64]
Pods/RadarSDK/dist/RadarSDK.xcframework/ios-arm64_armv7/RadarSDK.framework/RadarSDK (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
Pods/RadarSDK/dist/RadarSDK.xcframework/ios-arm64_armv7/RadarSDK.framework/RadarSDK (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```
**Notice the 'dynamically linked shared library'**
### If static the output would be
```Bash
Vendor/Frameworks/realm-objc-3.21.0/Realm.xcframework/ios-arm64/Realm.framework/Realm: Mach-O universal binary with 1 architecture: [arm64:current ar archive]
Vendor/Frameworks/realm-objc-3.21.0/Realm.xcframework/ios-arm64/Realm.framework/Realm (for architecture arm64):	current ar archive
```
**Notice the 'current ar archive'**

## OS version
`iOS 15`

## SDK installation method
Using CocoaPods `1.11.2` with `Podfile`:
```Ruby
use_frameworks! :linkage => :static

pod 'RadarSDK' , '= 3.2.4'
```

## SDK version
`3.2.4`

**Comment by jrtibbetts** [comment]
Thanks for contacting us, @hendych. An upcoming release of the SDK will build from source files, instead of using a pre-compiled XCFramework file, so you'll have more control over how it's built for your project.

**Comment by jrtibbetts** [comment]
The [`3.3.1` release](https://github.com/radarlabs/radar-sdk-ios/releases/tag/3.3.1) is now built from source. When you have a chance, give it a try and let us know whether you got it to build as a static XCFramework.

**Comment by jrtibbetts** [comment]
Closing this and marking it as finished.
