### ISSUE TITLE
Dependency "radar-sdk-ios" has no shared framework schemes

### ISSUE THREAD

**Issue by smartdevdom** [radarlabs/radar-sdk-ios#2]
With carthage update

**Comment by nickpatrick** [comment]
This should be fixed. We just had to attach the zipped framework to the GitHub release. https://github.com/radarlabs/radar-sdk-ios/releases/tag/1.2.26

Run `carthage update` again, and don't forget to drag `Build/iOS/RadarSDK.framework` into the Linked Frameworks and Libraries section of your target. https://www.onradar.com/documentation/sdk#ios-add

**Comment by smartdevdom** [comment]
Thansk
