### ISSUE TITLE
Location updates Queue

### ISSUE THREAD

**Issue by hernangonzalez** [radarlabs/radar-sdk-ios#30]
Hi,

Looks like calls to manually report updated locations needs to be called on the main queue. I started seeing this warnings:
```=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication backgroundTimeRemaining]
PID: 6972, TID: 1533917, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   Polarsteps                          0x00000001010d7578 -[RadarStateManager updateState:withSource:] + 1052
5   Polarsteps                          0x00000001010d7068 +[RadarStateManager updateState:withSource:] + 88
6   Polarsteps                          0x00000001010dfaf8 +[Radar forceTrack:handler:] + 172
7   Polarsteps                          0x00000001010df9ec +[Radar updateLocation:withCompletionHandler:] + 172
```

Is that something the SDK should handle on per need basis maybe? 
Otherwise maybe update the documentation to reflect that?

Cheers,
H..

**Comment by coolbrow** [comment]
Yeah, for now all SDK methods should be called on the main thread - we're working on improving this for future releases. In the meantime, we'll make sure our documentation reflects this, thanks for the report.
