### ISSUE TITLE
RadarPlace returns facebookPlaceId which facebook graph cannot find

### ISSUE THREAD

**Issue by DavidTomic** [radarlabs/radar-sdk-ios#33]
Hi,

I am using RadarSDK 2.0.0 for facebook places.

I get RadarEvent with RadarPlace object in it, but that object sometimes contains facebookPlaceId which facebook graph cannot find, e.g. this id: 326477860701555

Can you check that, thank you.

btw. I see RadarPlace has two facebook ids, can you tell me what the difference between those two are, thank you?

```
@property (nullable, copy, nonatomic, readonly) NSString *facebookId;
@property (nullable, copy, nonatomic, readonly) NSString *facebookPlaceId;
```

**Comment by nickpatrick** [comment]
Hi @DavidTomic, we ingest place data from multiple sources, so `facebookId` (old page ID) and `facebookPlaceId` (new place ID) may be stale or `nil`.

**Comment by DavidTomic** [comment]
Hi @nickpatrick, sry for bothering you, but I think Radar is offering the feature which is completely unreliable because it is returning the ids which are not usable.

That is, Radar gives me information that I am near some Facebook place but I cannot do anything with it because the id of that place is wrong, I didn't expect this.

**Comment by nickpatrick** [comment]
Can you help me understand what you want to do with the Facebook place IDs?

**Comment by DavidTomic** [comment]
@nickpatrick I am fetching from Facebook graph API place informations (images, working hours etc.) and present them inside my iOS app.
