### ISSUE TITLE
Breaking change was introduced with Minor version update

### ISSUE THREAD

**Issue by BenTincher** [radarlabs/radar-sdk-ios#346]
## Summary
Our app automatically upgraded from 3.11.2 to latest release over the weekend causing app failure.

It appears a mandatory delegate method was added to RadarDelegate which qualifies as a breaking change.

## SDK installation method
 SPM

**Comment by lmeier** [comment]
Hey @BenTincher — apologies for the breaking change.

If you don't mind, please pin the minor version for our SDK. I'm adding this as an instruction in our documentation as well. Our team sometimes release breaking changes as new minor versions.

Sorry again for the inconvenience.

**Comment by BenTincher** [comment]
No problem; conformance was easy enough to add in this case.  Just thought you might want a heads up; appreciate it.
