### ISSUE TITLE
Would be nice with a Swift Package Manager option as well :)

### ISSUE THREAD

**Issue by ShvetsJr** [radarlabs/radar-sdk-ios#92]
## Summary

Would it be possible to add a SPM support in near future?

**Comment by nickpatrick** [comment]
@ShvetsJr XCFramework and Swift Package Manager support were added in the https://github.com/radarlabs/radar-sdk-ios/releases/tag/3.2.0-beta.1 release. Give it a try and let us know if it works for you. A non-beta 3.2.0 release will be coming in the next few weeks.
